### ISSUE TITLE
Incorrect Jboss profile link and missing hardening link

### ISSUE THREAD

**Issue by ejaronne** [mitre/mitre-saf#121]
The JBoss profile link is incorrectly pointing to the chef_hardening repo:
![image](https://user-images.githubusercontent.com/34140975/91565728-a8440500-e910-11ea-89b6-05f1c0937984.png)

it should be pointing to https://github.com/mitre/red-hat-jboss-eap-6.3-stig-baseline

...and the hardening page doesn't show the JBoss chef hardening

**Comment by wdower** [comment]
@ejaronne Do you mean that the JBoss link should be pointing to https://github.com/mitre/red-hat-jboss-eap-6.3-stig-baseline, as opposed to https://github.com/mitre/chef-red-hat-jboss-eap-6.3-stig-baseline ? Not sure why the JBoss link should go to RSA Archer.

Also, do you know where the JBoss chef hardening profile lives? I must not have seen it when I was adding profiles. Do we have it in github.com/mitre?
