### ISSUE TITLE
Add harden content to SAF website

### ISSUE THREAD

**Issue by georgedias** [mitre/mitre-saf#329]
Link available Ansible, Chef, and PowerShell DSC content to SAF website (harden or validate) as appropriate from [DoD Cyber Exchange Supplemental Automation Content](https://public.cyber.mil/stigs/supplemental-automation-content/)

**Comment by wdower** [comment]
Added to hardening page. Did not add:

- Red Hat Enterprise Linux 7 STIG for Ansible - Ver 3, Rel 3
- Microsoft Windows Server 2016 STIG for Chef - Ver 1, Rel 3
- Microsoft Windows Server 2019 STIG for Chef - Ver 1, Rel 2

because we already have STIG content from other sources for that STIG.
