### ISSUE TITLE
Enable and monitor saf email address

### ISSUE THREAD

**Issue by ejaronne** [mitre/mitre-saf#34]
as of 12/24/2019, saf@groups.mitre.org doesn't work. Not sure who is planning to enable it or monitor it.

**Comment by wdower** [comment]
I submitted a form to create an office 365 group with that email. They expect a 2 day turnaround on approval.

**Comment by ejaronne** [comment]
I updated the mailbox title and description to:
Secur**_ity_** Automation Framework
"The MITRE Security Automation Framework (SAF) brings together applications, techniques, libraries, and tools developed by MITRE and the security community to streamline security automation for systems and DevOps pipelines. https://mitre-saf.netlify.com/ "

**Comment by wdower** [comment]
Email is working (and typo-free).
