### ISSUE TITLE
Make the list of heimdall_tools' supported tools update automatically

### ISSUE THREAD

**Issue by wdower** [mitre/mitre-saf#351]
New mappers keep getting added to the supported list for Heimdall tools and it's going to be hard to maintain. Would be nice if we could store a list of supported tools in heimdall_tools' own GH repo and just grab the data for the SAF site from there. That way whenever a PR to Heimdall_tools adds a new mapper, the SAF site's Normalize and FAQ pages that talk about Heimdall Tools would get the new mappers automatically.

Would also be nice if the Heimdall_tools README could do the same trick and import the list somehow.

**Comment by Amndeep7** [comment]
Which I think you've already implemented so closing.
