### ISSUE TITLE
Refactr <> Sophos Logo Update

### ISSUE THREAD

**Issue by refactrmike** [mitre/mitre-saf#357]
We would like to get the Refactr logo updated to the attached Sophos logo on https://saf.mitre.org

[sophos-logo-blue-rgb.svg.zip](https://github.com/mitre/mitre-saf/files/7872415/sophos-logo-blue-rgb.svg.zip)

**Comment by wdower** [comment]
Hi @refactrmike -- thanks for the image.

Just to clarify, the partner images also link to the partner's site -- should we link people to [Refactr](https://www.refactr.it/) or to [Sophos](https://www.sophos.com/en-us.aspx)?
