### ISSUE TITLE
Replace Splunk Plugin with saf convert hdf2*

### ISSUE THREAD

**Issue by camdenmoors** [mitre/mitre-saf#379]
Now we support conversion of multiple formats from HDF and this should be included instead of the older Splunk under the normalize pillar. Also the saf cli uses spaces instead of colons as separators.

![plugin](https://user-images.githubusercontent.com/66680985/163591321-7f84243a-5ed8-456c-81fe-d20840afad4b.png)

**Comment by ejaronne** [comment]
remove the word "plugin" from the tile and redirect to https://github.com/mitre/saf/blob/main/README.md#hdf-to-splunk
